CREATE TABLE "Roles" (
  "id" integer PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "description" varchar(100) NOT NULL
);

CREATE TABLE "Permissions" (
  "id" integer PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "description" varchar(100) NOT NULL
);

CREATE TABLE "RolePermissions" (
  "role_id" integer,
  "permission_id" integer,
  PRIMARY KEY ("role_id", "permission_id")
);

CREATE TABLE "Accounts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "login" varchar(100) UNIQUE NOT NULL,
  "password_hash" text NOT NULL,
  "role_id" integer NOT NULL
);

CREATE TABLE "Sessions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" bigint NOT NULL,
  "access_token_hash" varchar(64) UNIQUE NOT NULL,
  "access_token_expires_at" timestamptz NOT NULL DEFAULT (now() + interval '15 minutes'),
  "refresh_token_hash" varchar(64) UNIQUE NOT NULL,
  "refresh_token_expires_at" timestamptz NOT NULL DEFAULT (now() + interval '7 days'),
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "last_used_at" timestamptz,
  "revoked_at" timestamptz
);

CREATE INDEX ON "Accounts" ("role_id");

CREATE INDEX ON "Sessions" ("account_id");

CREATE INDEX ON "Sessions" ("access_token_expires_at", "revoked_at");

CREATE INDEX ON "Sessions" ("refresh_token_expires_at", "revoked_at");

COMMENT ON TABLE "Roles" IS 'Роли, определенные в системе';

COMMENT ON COLUMN "Roles"."name" IS 'Кодовое имя роли: Роль по умолчанию (без прав), Админ, Оператор КТП, Оператор WFM, Представитель клиента и т.д.';

COMMENT ON COLUMN "Roles"."description" IS 'Описание роли';

COMMENT ON TABLE "Permissions" IS 'Права, определенные в системе';

COMMENT ON COLUMN "Permissions"."name" IS 'Кодовое имя права';

COMMENT ON COLUMN "Permissions"."description" IS 'Описание права';

COMMENT ON TABLE "RolePermissions" IS 'Сопоставление ролей и прав';

COMMENT ON TABLE "Accounts" IS 'Учетные записи пользователей';

COMMENT ON TABLE "Sessions" IS 'Открытые сессии пользователей';

COMMENT ON COLUMN "Sessions"."access_token_hash" IS 'Хеш токена, используемого для авторизации запросов пользователя. Храниться в SHA-256';

COMMENT ON COLUMN "Sessions"."refresh_token_hash" IS 'Хеш токена, используемого для перевыпуска пары токенов по истечении их времени жизни. Храниться в SHA-256';

ALTER TABLE "RolePermissions" ADD FOREIGN KEY ("role_id") REFERENCES "Roles" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "RolePermissions" ADD FOREIGN KEY ("permission_id") REFERENCES "Permissions" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "Accounts" ADD FOREIGN KEY ("role_id") REFERENCES "Roles" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION;

ALTER TABLE "Sessions" ADD FOREIGN KEY ("account_id") REFERENCES "Accounts" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION;
