-- +goose Up

-- Создаем схемы
CREATE SCHEMA IF NOT EXISTS "auth";
CREATE SCHEMA IF NOT EXISTS "profiles";
CREATE SCHEMA IF NOT EXISTS "hrm";
CREATE SCHEMA IF NOT EXISTS "crm";

-- ────────────────────────────────────────────────────────────────────────────
-- AUTH SCHEMA
-- ────────────────────────────────────────────────────────────────────────────

-- Роли, определенные в системе
CREATE TABLE "auth"."Roles" (
  "id" INTEGER PRIMARY KEY,
  "name" VARCHAR(50) UNIQUE NOT NULL,
  "description" VARCHAR(100) NOT NULL
);

COMMENT ON TABLE "auth"."Roles" IS 'Роли, определенные в системе';
COMMENT ON COLUMN "auth"."Roles"."name" IS 'Кодовое имя роли: Роль по умолчанию (без прав), Админ, Оператор КТП, Оператор WFM, Представитель клиента и т.д.';
COMMENT ON COLUMN "auth"."Roles"."description" IS 'Описание роли';

-- Права, определенные в системе
CREATE TABLE "auth"."Permissions" (
  "id" INTEGER PRIMARY KEY,
  "name" VARCHAR(100) UNIQUE NOT NULL,
  "description" VARCHAR(100) NOT NULL
);

COMMENT ON TABLE "auth"."Permissions" IS 'Права, определенные в системе';
COMMENT ON COLUMN "auth"."Permissions"."name" IS 'Кодовое имя права';
COMMENT ON COLUMN "auth"."Permissions"."description" IS 'Описание права';

-- Сопоставление ролей и прав
CREATE TABLE "auth"."RolePermissions" (
  "role_id" INTEGER,
  "permission_id" INTEGER,
  PRIMARY KEY ("role_id", "permission_id"),
  FOREIGN KEY ("role_id") REFERENCES "auth"."Roles" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
  FOREIGN KEY ("permission_id") REFERENCES "auth"."Permissions" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE
);

COMMENT ON TABLE "auth"."RolePermissions" IS 'Сопоставление ролей и прав';

-- Учетные записи пользователей
CREATE TABLE "auth"."Accounts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "login" VARCHAR(100) UNIQUE NOT NULL,
  "password_hash" TEXT NOT NULL,
  "role_id" INTEGER NOT NULL,
  FOREIGN KEY ("role_id") REFERENCES "auth"."Roles" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE
);

CREATE INDEX ON "auth"."Accounts" ("role_id");

COMMENT ON TABLE "auth"."Accounts" IS 'Учетные записи пользователей';

-- Открытые сессии пользователей
CREATE TABLE "auth"."Sessions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" BIGINT NOT NULL,
  "access_token_hash" VARCHAR(64) UNIQUE NOT NULL,
  "access_token_expires_at" TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '15 minutes'),
  "refresh_token_hash" VARCHAR(64) UNIQUE NOT NULL,
  "refresh_token_expires_at" TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '7 days'),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT (NOW()),
  "last_used_at" TIMESTAMPTZ,
  "revoked_at" TIMESTAMPTZ,
  FOREIGN KEY ("account_id") REFERENCES "auth"."Accounts" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE
);

CREATE INDEX ON "auth"."Sessions" ("account_id");
CREATE INDEX ON "auth"."Sessions" ("access_token_expires_at", "revoked_at");
CREATE INDEX ON "auth"."Sessions" ("refresh_token_expires_at", "revoked_at");

COMMENT ON TABLE "auth"."Sessions" IS 'Открытые сессии пользователей';
COMMENT ON COLUMN "auth"."Sessions"."access_token_hash" IS 'Хеш токена, используемого для авторизации запросов пользователя. Хранится в SHA-256';
COMMENT ON COLUMN "auth"."Sessions"."refresh_token_hash" IS 'Хеш токена, используемого для перевыпуска пары токенов по истечении их времени жизни. Хранится в SHA-256';

-- ────────────────────────────────────────────────────────────────────────────
-- PROFILES SCHEMA
-- ────────────────────────────────────────────────────────────────────────────

-- Профили пользователей системы EBKO_CRM
CREATE TABLE "profiles"."Profiles" (
  "account_id" BIGINT PRIMARY KEY,
  "full_name" VARCHAR(150) NOT NULL,
  "phone_number" VARCHAR(20) UNIQUE NOT NULL,
  "email" VARCHAR(254) UNIQUE NOT NULL,
  "image" BYTEA,
  "birth_date" DATE,
  "position" VARCHAR(100),
  FOREIGN KEY ("account_id") REFERENCES "auth"."Accounts" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE
);

COMMENT ON TABLE "profiles"."Profiles" IS 'Профили пользователей системы EBKO_CRM';
COMMENT ON COLUMN "profiles"."Profiles"."full_name" IS 'ФИО пользователя';
COMMENT ON COLUMN "profiles"."Profiles"."phone_number" IS 'Контактный номер пользователя';
COMMENT ON COLUMN "profiles"."Profiles"."email" IS 'Адрес электронной почты пользователя';
COMMENT ON COLUMN "profiles"."Profiles"."image" IS 'Аватарка пользователя';
COMMENT ON COLUMN "profiles"."Profiles"."birth_date" IS 'Дата рождения пользователя';
COMMENT ON COLUMN "profiles"."Profiles"."position" IS 'Должность пользователя';

-- ────────────────────────────────────────────────────────────────────────────
-- HRM SCHEMA
-- ────────────────────────────────────────────────────────────────────────────

-- Расширение профиля для сотрудников компании, использующей EBKO_CRM
CREATE TABLE "hrm"."Employees" (
  "account_id" BIGINT PRIMARY KEY,
  "hire_date" DATE,
  FOREIGN KEY ("account_id") REFERENCES "profiles"."Profiles" ("account_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE
);

COMMENT ON TABLE "hrm"."Employees" IS 'Расширение профиля для сотрудников компании, использующей EBKO_CRM';
COMMENT ON COLUMN "hrm"."Employees"."hire_date" IS 'Дата приёма на работу';

-- ────────────────────────────────────────────────────────────────────────────
-- CRM SCHEMA
-- ────────────────────────────────────────────────────────────────────────────

-- Перечень компаний-клиентов
CREATE TABLE "crm"."Clients" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) UNIQUE NOT NULL,
  "address" VARCHAR(500) NOT NULL
);

COMMENT ON TABLE "crm"."Clients" IS 'Перечень компаний-клиентов';
COMMENT ON COLUMN "crm"."Clients"."name" IS 'Название компании-клиента в системе CRM';
COMMENT ON COLUMN "crm"."Clients"."address" IS 'Адрес головного офиса компании-клиента';

-- Контакты CEO компании-клиента
CREATE TABLE "crm"."ClientCEO_Contacts" (
  "client_id" BIGINT PRIMARY KEY,
  "phone_number" VARCHAR(20) UNIQUE NOT NULL,
  "email" VARCHAR(254) UNIQUE NOT NULL,
  FOREIGN KEY ("client_id") REFERENCES "crm"."Clients" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE
);

COMMENT ON TABLE "crm"."ClientCEO_Contacts" IS 'Контакты CEO компании-клиента';
COMMENT ON COLUMN "crm"."ClientCEO_Contacts"."phone_number" IS 'Контактный номер CEO компании-клиента';
COMMENT ON COLUMN "crm"."ClientCEO_Contacts"."email" IS 'Адрес электронной почты CEO компании-клиента';

-- Расширение профиля для представителей компаний-клиентов
CREATE TABLE "crm"."Representatives" (
  "account_id" BIGINT PRIMARY KEY,
  FOREIGN KEY ("account_id") REFERENCES "profiles"."Profiles" ("account_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE
);

COMMENT ON TABLE "crm"."Representatives" IS 'Расширение профиля для представителей компаний-клиентов';

-- Сопоставление компаний-клиентов и их представителей
CREATE TABLE "crm"."ClientRepresentatives" (
  "client_id" BIGINT,
  "representative_id" BIGINT,
  PRIMARY KEY ("client_id", "representative_id"),
  FOREIGN KEY ("client_id") REFERENCES "crm"."Clients" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
  FOREIGN KEY ("representative_id") REFERENCES "crm"."Representatives" ("account_id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE
);

CREATE INDEX ON "crm"."ClientRepresentatives" ("representative_id");

COMMENT ON TABLE "crm"."ClientRepresentatives" IS 'Сопоставление компаний-клиентов и их представителей';

-- Площадки компаний-клиентов
CREATE TABLE "crm"."Sites" (
  "id" BIGINT PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "address" VARCHAR(500) NOT NULL
);

COMMENT ON TABLE "crm"."Sites" IS 'Площадки компаний-клиентов';
COMMENT ON COLUMN "crm"."Sites"."name" IS 'Название площадки компании-клиента';
COMMENT ON COLUMN "crm"."Sites"."address" IS 'Адрес площадки компании-клиента';

-- Сопоставление компаний-клиентов и их площадок
CREATE TABLE "crm"."ClientSites" (
  "client_id" BIGINT,
  "site_id" BIGINT,
  PRIMARY KEY ("client_id", "site_id"),
  FOREIGN KEY ("client_id") REFERENCES "crm"."Clients" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
  FOREIGN KEY ("site_id") REFERENCES "crm"."Sites" ("id") ON DELETE CASCADE ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE
);

CREATE INDEX ON "crm"."ClientSites" ("site_id");

COMMENT ON TABLE "crm"."ClientSites" IS 'Сопоставление компаний-клиентов и их площадок';

-- +goose Down

DROP TABLE IF EXISTS "crm"."ClientSites";
DROP TABLE IF EXISTS "crm"."Sites";
DROP TABLE IF EXISTS "crm"."ClientRepresentatives";
DROP TABLE IF EXISTS "crm"."Representatives";
DROP TABLE IF EXISTS "crm"."ClientCEO_Contacts";
DROP TABLE IF EXISTS "crm"."Clients";
DROP TABLE IF EXISTS "hrm"."Employees";
DROP TABLE IF EXISTS "profiles"."Profiles";
DROP TABLE IF EXISTS "auth"."Sessions";
DROP TABLE IF EXISTS "auth"."Accounts";
DROP TABLE IF EXISTS "auth"."RolePermissions";
DROP TABLE IF EXISTS "auth"."Permissions";
DROP TABLE IF EXISTS "auth"."Roles";

DROP SCHEMA IF EXISTS "crm";
DROP SCHEMA IF EXISTS "hrm";
DROP SCHEMA IF EXISTS "profiles";
DROP SCHEMA IF EXISTS "auth";
